<?php

namespace app\admin\controller;
use think\Controller;
use think\facade\Session;


class Common extends Controller
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        if (!Session::has('admin')){
            $this->error('请登录','/admin/login/index');
        }
    }


}
