<?php

namespace app\index\controller;

use think\Controller;
use think\Db;

class Common extends Controller
{
   public function initialize()
   {
       parent::initialize(); // TODO: Change the autogenerated stub
       //获取公告列表
       $affiche=Db::name('affiche')->order('aff_order','desc')->select();
       //获取顶级分类
       $topCates = Db::name('cate')->where('cate_pid', '=', 0)->all();
       //获取标签数据
       $tags = Db::name('tag')->all();
       //获取分类数据
//       $cates = Db::name('cate')->all();
       $this->assign(['tags' => $tags,'affiche'=>$affiche]);
   }
}
