<?php

namespace app\index\controller;

use think\Controller;
use think\Request;


class Test extends Controller
{
    public function aa()
    {
        return view('/test1');
    }
    public function index()
    {
        $this->error('哈哈', '1');
        return $this->fetch();
        //        $this->success('成功',);
    }
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function cc()
    {
        var_dump(input('param.'));
        var_dump(input('get.'));
    }

    public function rr()
    {
        /*redis()->set('task_num_1',3);
        $num = redis()->get('task_num_1');
        halt(redis()->keys('*'));
        halt($num);
        return $this->fetch();*/
        $name = 'aaa';
        redis()->incr($name);
        redis()->expire($name, 1000);
        echo redis()->get($name);
    }

    public function in()
    {
        $obj = new Test();
        $obj(122);
        var_dump(is_callable($obj));
    }


    function __invoke($x)
    {
        var_dump($x);
    }

    public function hello(Request $request)
    {
        return 'Hello,' . $request->param('name') . '！111';
    }
}


/*class CallableClass
{
    function __invoke($x)
    {
        var_dump($x);
    }
}

$obj = new CallableClass;
$obj(5);
var_dump(is_callable($obj));*/
